# applies to podtato-head-entry deployment only
# this line is just a test for upstream/downstream mgmt tests
# another thing we change in upstream, which should also go downstream
ingress:
  className: nginx
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: team-a-antonius-test.lab.suxessit.k8s.cloud.uibk.ac.at
    dns.gardener.cloud/ttl: "180"
    # another comment from upstream should go to downstream
    # and this one
  hosts:
    - host: team-a-antonius-test.lab.suxessit.k8s.cloud.uibk.ac.at
      paths:
        - path: /
          pathType: ImplementationSpecific
